### ISSUE TITLE
Sentences that possibly miss something

### ISSUE THREAD

**Issue by badeaffe** [standardebooks/upton-sinclair_the-jungle#13]
Hello,

I’ve stumbled across some sentences that make no sense to me, maybe they each miss some word or something, or maybe I just don’t get their grammar. These are not transcription errors, that I’ve checked.

* Chapter III: “There were some with hose which threw jets of boiling water upon it”
* Chapter IV: “there was nothing could scare a man who had been with a railroad-gang”
* Chapter XV: “Things swam blood before him, and he screamed aloud in his fury”
* Chapter XXV: “He voted half a dozen times himself, and voted some of his friends as often”

Any ideas for corrections?

**Comment by acabal** [comment]
If these are as-is in the page scans, we would not change them.
