### ISSUE TITLE
The German-speaking Dutch Madame

### ISSUE THREAD

**Issue by badeaffe** [standardebooks/upton-sinclair_the-jungle#14]
Hello,

chapter XIX features

> Madame Haupt, Hebamme,
> a Dutch woman

However, this Madame is evidently not Dutch but German, and that is some dilettante German to be sure. I’m wondering if this calls for some editorial edits? I’d like to change “Gott in Himmel” to “Gott im Himmel” and “Herr Gott!” to “Herrgott!”. Are those edits in line with Standard Ebooks practices?

**Comment by acabal** [comment]
Sure. Sinclair was mostly going by ear in terms of non-English spelling. I recall I fixed his Lithuanian too.

**Comment by badeaffe** [comment]
Alright, I’ll prepare the pull request.
